### ISSUE TITLE
Push is failing because jenkins is out of disk

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/cgl-docker-lib#100]
Snipped from [jenkins build 116](http://jenkins.cgcloud.info/job/cgl-docker-lib/116/consoleFull):

```
Error response from daemon: mkdir /var/lib/docker/tmp/docker-build451302929: no space left on device
make: *** [apache-hadoop-common] Error 1
# Requires ~/.dockercfg
docker push quay.io/ucsc_cgl/gatk:3.5--dba6dae49156168a909c43330350c6161dc7ecc2
The push refers to a repository [quay.io/ucsc_cgl/gatk] (len: 1)
613269e6f67f: Buffering to Disk
mkdir /var/lib/docker/graph/_tmp/2ed673c39822f723df9d1018153ff0d66308fe8c38808e3962687a4fc6f7e7e5: no space left on device
make: *** [push] Error 1
```

@hannes-ucsc any chance we could get this cleaned up so that we can get point at #99 from https://github.com/BD2KGenomics/toil-scripts/pull/187?

**Comment by hannes-ucsc** [comment]
Looking now.

**Comment by hannes-ucsc** [comment]
Current docker-jenkins-slave didn't have /var/lib/docker mounted on ephemeral. This was a bug I fixed a while ago but never updated the AMI in Jenkins. Did that just now and triggered a build. Verified that /var/lib/docker is bind-mounted to ephemeral. Fingers crossed. Going to bed now.

**Comment by fnothaft** [comment]
Thanks @hannes-ucsc ! The last `cgl-docker-lib` build pushed successfully.
