### ISSUE TITLE
Containerize Mesos and Toil

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/cgl-docker-lib#115]

**Comment by jvivian** [comment]
I figure we can just use the official mesos containers from dockerhub
@cket — Let me know if you can get these to work on AWS, I'll try to see if I can get them working on Openstack. 

https://hub.docker.com/r/mesoscloud/mesos-master/

```
docker run -d \
-e MESOS_HOSTNAME=ip.address \
-e MESOS_IP=ip.address \
-e MESOS_QUORUM=2 \
-e MESOS_ZK=zk://node-1:2181,node-2:2181,node-3:2181/mesos \
--name mesos-master --net host --restart always \
mesoscloud/mesos-master:0.24.1-ubuntu-14.04
```

Set environment variable SECRET to enable framework and slave authentication.

https://hub.docker.com/r/mesoscloud/mesos-slave/

```
docker run -d \
-e MESOS_HOSTNAME=ip.address \
-e MESOS_IP=ip.address \
-e MESOS_MASTER=zk://node-1:2181,node-2:2181,node-3:2181/mesos \
-v /sys/fs/cgroup:/sys/fs/cgroup \
-v /var/run/docker.sock:/var/run/docker.sock \
--name slave --net host --privileged --restart always \
mesoscloud/mesos-slave:0.24.1-ubuntu-14.04
```

Set environment variable SECRET to enable slave authentication.

**Comment by jvivian** [comment]
<img width="1164" alt="screen shot 2016-04-25 at 6 48 36 pm" src="https://cloud.githubusercontent.com/assets/7576256/14804274/a66f38e4-0b16-11e6-806e-8323b437b3b0.png">

I'll try running a toil pipeline to see if I run into any issues.  For OpenStack I couldn't use the associated floating IP but instead had to use the internal IP.   

Command on master:

```
docker run -d \
-e SECRET=foo \
-e MESOS_HOSTNAME=10.101.0.21 \
-e MESOS_IP=10.101.0.21 \
--name mesos-master \
--net host \
--restart always mesoscloud/mesos-master:0.24.1-ubuntu-14.04 
```

Command on slave:

```
docker run -d \
-e SECRET=foo \
-e MESOS_HOSTNAME=10.101.0.22 \
-e MESOS_IP=10.101.0.22 \
-e MESOS_MASTER=10.101.0.21:5050 \
-v /sys/fcgroup:/sys/fs/cgroup \
-v /var/run/docker.sock:/var/run/docker.sock \
--name slave \
--net host \
--privileged \
--restart always mesoscloud/mesos-slave:0.24.1-ubuntu-14.04
```

**Comment by jvivian** [comment]
Biggest issue I'm running into is that Toil still needs mesos.native, but even inside the container mesos.native isn't installed.   I'm also having issues where the mesos/native subdir is being installed in a separate location than other pip packages which is quite a headache. 

Also, if we have to install mesos.native on the master anyway, that sort of defeats the purpose of the mesos container in the first place.

**Comment by hannes-ucsc** [comment]
Look at cgcloud's DockerBox for a recipe on how to install the Mesos egg that contains mesos.native. Either rip their Dockerfile and modify it (check license before you do that) or base your own Dockerfile on theirs via FROM.

Also, 0.24.1 is rather old.

**Comment by jvivian** [comment]
Ya, looking at CGCloud source was my next step — Toil docs say we've only tested up to 0.25, should I be trying to use the newest 0.28.0?

**Comment by hannes-ucsc** [comment]
Let's try to stick with 0.25 for now. The same version that cgcloud installs.

The move to the latest stable Mesos release should be a separate effort.

**Comment by jvivian** [comment]
@hannes-ucsc — Let's schedule a time to review what I have so far and then we can close this ticket.

**Comment by hannes-ucsc** [comment]
@jvivian, I think it is sufficient if you file a PR with what you have. I'll take it from there towards #105 of which this ticket is a dupe.

**Comment by jvivian** [comment]
PR filed, closing.
