### ISSUE TITLE
README should explain (and suggest redirect of) location of Synapse output

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgl-docker-lib#118]
I followed the `cgl-docker-lib/rnaseq-cgl-pipeline/README.md`

It turns out that Synapse stores downloaded files in the user's home directory, under `~/.synapseCache/`. Synapse actually tells you this while it's downloading, but it still took me a while to locate the files, which I had expected to be in python's workdir. Since the sysadmins aren't happy about me putting 27G of data in my `$HOME`, maybe it's worth suggesting a symlink of `.synapseCache` to a more data friendly location?

**Comment by jvivian** [comment]
Great point — I just looked at the source code and see that `get()` has kwargs for `downloadLocation`, so i'll add that clarification to the docs.
