### ISSUE TITLE
Check out BioBoxes and Elixir

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/cgl-docker-lib#15]

**Comment by jvivian** [comment]
Bioboxes has a great mission statement:

"We believe a community standard, using software containers, has the opportunity to solve the current software usability problems and increase the standard of scientific software as a whole. A standard for bioinformatics containers will move us towards a more open environment for anyone to innovate, collaborate and share their scientific software. Working in a truly standardized and interoperable ecosystem, will allow bioinformatics algorithmic developments to become useful to everyone."

But doesn't really deliver on it.   They've only created containers for aligners, with the idea that once you can use one "biobox aligner" you can interchangeably use any of them, but I personally don't think that's a very feasible idea that's generalizable to every bioinformatics tool.  You can only create standards for containerizing the tool, not define standards for how you'd provide inputs / handle output.

**Comment by heuermh** [comment]
> You can only create standards for containerizing the tool, not define standards for how you'd provide inputs / handle output.

Regarding this, you may want to take a look at the CWL effort:
https://github.com/common-workflow-language/common-workflow-language

**Comment by hannes-ucsc** [comment]
CWL has been on our radar, and dropped off, but we should probably check it out again.

Re: bioboxes, it looks like there is no there there. The interchangeability of containers sounds impossible to me. We are instead aiming for the ability to substitute the container for the tool which is lower hanging, more pragmatic fruit.
