### ISSUE TITLE
Add ability to collect files on the master

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgl-docker-lib#16]
We need a way to get files produced by jobs back to the master.  Imagine a deep job DAG where jobs write partial results to a file and return the file id to their follow-on. The follow-on collects the child result file IDs  into a list and returns the list to its follow-on. The root sets up a follow-on that aggregates all those lists into a single list, reads all files in the list and concatenates them into a single, large, locally stored large result file. That file however will reside on one of the worker nodes. We need a way to get the file back to the master.

**Comment by jvivian** [comment]
Is this in the wrong repo?

**Comment by hannes-ucsc** [comment]
Yes. See BD2KGenomics/toil#618 and BD2KGenomics/toil#619.
