### ISSUE TITLE
Zero length bam files

### ISSUE THREAD

**Issue by rcurrie** [BD2KGenomics/cgl-docker-lib#215]
Pipeline often generates zero length bam files with no error and still generates expression levels making it impossible to run the QC pipeline as it requires the bam file.

Ran 35 fastq pairs with the results all under:

/pod/pstore/groups/treehouse/backed_up/archive/output/externalSamples/phs000699.v1.p1_OSGenomics

For the final 12 I backhauled the bam generated and of those 9 were zero length:

/pod/pstore/groups/treehouse/backed_up/archive/output/externalSamples/phs000699.v1.p1_OSGenomics

Full log output of these 12 is at:

/pod/pstore/groups/treehouse/backed_up/archive/output/externalSamples/phs000699.v1.p1_OSGenomics/log.txt

(run on 3 machines so output is interleaved with IP address as the prefix)

**Comment by jvivian** [comment]
@rcurrie — Where can I get a sample that I can use to replicate?

**Comment by rcurrie** [comment]
Sorry, meant to be more explicit with repo. Here's a specific set from the above 12:

Generated Zero Length:
/pod/pstore/groups/treehouse/published-data/dbGap/phs000699.v1.p1/data/fastq/SRR1701137_1.fastq.gz
/pod/pstore/groups/treehouse/published-data/dbGap/phs000699.v1.p1/data/fastq/SRR1701137_2.fastq.gz

Generated Non-Zero Length
/pod/pstore/groups/treehouse/published-data/dbGap/phs000699.v1.p1/data/fastq/SRR1701256_1.fastq.gz
/pod/pstore/groups/treehouse/published-data/dbGap/phs000699.v1.p1/data/fastq/SRR1701256_2.fastq.gz

Here are the 12 that ran with mixed results with output in the above mentioned log.txt:

Under:
/pod/pstore/groups/treehouse/backed_up/archive/output/externalSamples/phs000699.v1.p1_OSGenomics
-rw-r--r-- 1 rcurrie pawg    0 Dec 10 12:33 ./SRR1701137/SRR1701137.sorted.bam
-rw-r--r-- 1 rcurrie pawg    0 Dec 10 18:54 ./SRR1701216/SRR1701216.sorted.bam
-rw-r--r-- 1 rcurrie pawg  26G Dec  9 15:53 ./SRR1701256/SRR1701256.sorted.bam
-rw-r--r-- 1 rcurrie pawg    0 Dec 10 08:44 ./SRR1701272/SRR1701272.sorted.bam
-rw-r--r-- 1 rcurrie pawg    0 Dec 10 02:42 ./SRR1701369/SRR1701369.sorted.bam
-rw-r--r-- 1 rcurrie pawg    0 Dec 10 10:08 ./SRR1701489/SRR1701489.sorted.bam
-rw-r--r-- 1 rcurrie pawg    0 Dec  9 18:16 ./SRR1701598/SRR1701598.sorted.bam
-rw-r--r-- 1 rcurrie pawg    0 Dec 10 02:06 ./SRR1701638/SRR1701638.sorted.bam
-rw-r--r-- 1 rcurrie pawg    0 Dec 10 16:28 ./SRR1701687/SRR1701687.sorted.bam
-rw-r--r-- 1 rcurrie pawg 8.6G Dec 10 12:42 ./SRR1701708/SRR1701708.sorted.bam
-rw-r--r-- 1 rcurrie pawg    0 Dec  9 16:58 ./SRR1701777/SRR1701777.sorted.bam
-rw-r--r-- 1 rcurrie pawg  17G Dec  9 23:00 ./SRR1701828/SRR1701828.sorted.bam

The source files paths are all in phs000699RnaSeqManifest.tsv in that same folder.

**Comment by rcurrie** [comment]
The pipeline was called using the 2.0.8 docker from a fabric file here:

https://github.com/UCSC-Treehouse/treeshop/blob/8db2d468ce34987891bd6953573a06b30c8c4e7a/fabfile.py#L89

and run distributed using docker-machine

**Comment by jvivian** [comment]
Thanks for the info @rcurrie — I have a couple other things I need to get to first today, but I'll take a look ASAP.

**Comment by rcurrie** [comment]
Sounds good and thanks!

**Comment by jvivian** [comment]
I don't have permissions to that directory (my username is `jvivian` on podk)

**Comment by rcurrie** [comment]
Try again.

In case it reads on the issue the samples were round robin processed one at a time on the following size machines:

15 core/5TB storage/125GB memory (openstack pod z1.medium)
6 core/2TB storage/48GB memory (openstack in pod z1.small)
16 core/800GB storage/112GB memory (azure D14)

**Comment by jvivian** [comment]
I was able to reproduce and correct this error when running STAR to produce the sorted bam.

In some sample cases, the sort bam step uses an unreasonable amount of memory (~30G paired sample using >250G memory). If this step fails, STAR doesn't exit with an exit code 0 (hence why there's no pipeline failure, just an empty BAM). 

I'm running another one of the samples that produced zero-length now to ensure that it also works. 

The fix is on a [branch right now](https://github.com/BD2KGenomics/toil-lib/commit/7510cd03e8579c8886883cb805409661400dc44c) which I'll PR against master then cherrypick over to the release branch for 1.1.1 which toil-rnaseq 3.0.0 will use.

**Comment by rcurrie** [comment]
Excellent - Thanks!

**Comment by jvivian** [comment]
@cket — resolve this issue when you PR the 3.0.1 Docker.
