### ISSUE TITLE
gencode_hugo_mapping docs

### ISSUE THREAD

**Issue by cchng** [BD2KGenomics/cgl-docker-lib#217]
Hi @jvivian ,

I'm looking into doing some gene model comparisons with genes given in UCSC's Treehouse data.
They pointed me to the source which led me to this gencode_hugo_mapping container.
Is there any documentation on this or is there a way I can obtain the gene models/canonical transcripts selected/used?

Thanks,
Carolyn

**Comment by hbeale** [comment]
@cchng I had this question recently myself, and @jvivian showed me that the mappings are based on the attrs tsv file in the git repo:
https://github.com/jvivian/docker_tools/tree/master/gencode_hugo_mapping

**Comment by jvivian** [comment]
Thanks for answering @hbeale ! 

Hi @cchng — The annotation file for the genes comes from [Gencode v23](https://www.gencodegenes.org/releases/23.html). 

The tsv @hbeale pointed to is the from the UCSC browser's hg38.wgEncodeGencodeAttrs table (V23 Gencode annotations).

You can see I'm mapping **geneId** to **geneName** to get the name.

Please re-open if you have any further questions!

**Comment by cchng** [comment]
Thanks! What do you do with one-many mappings? For example:
```
$ grep 5S_rRNA attrs.tsv 
ENSG00000252830.2	5S_rRNA	rRNA	NOVEL	ENST00000517021.2	5S_rRNA.3-201	rRNA	NOVEL				3	nonCoding
ENSG00000276442.1	5S_rRNA	rRNA	NOVEL	ENST00000621941.1	5S_rRNA.18-201	rRNA	NOVEL				3	nonCoding
ENSG00000274408.1	5S_rRNA	rRNA	NOVEL	ENST00000622298.1	5S_rRNA.13-201	rRNA	NOVEL				3	nonCoding
ENSG00000274059.1	5S_rRNA	rRNA	NOVEL	ENST00000618635.1	5S_rRNA.11-201	rRNA	NOVEL				3	nonCoding
ENSG00000277712.1	5S_rRNA	rRNA	NOVEL	ENST00000610374.1	5S_rRNA.26-201	rRNA	NOVEL				3	nonCoding
ENSG00000274097.1	5S_rRNA	rRNA	NOVEL	ENST00000617631.1	5S_rRNA.12-201	rRNA	NOVEL				3	nonCoding
ENSG00000273928.1	5S_rRNA	rRNA	NOVEL	ENST00000611128.1	5S_rRNA.10-201	rRNA	NOVEL				3	nonCoding
ENSG00000277488.1	5S_rRNA	rRNA	NOVEL	ENST00000618379.1	5S_rRNA.24-201	rRNA	NOVEL				3	nonCoding
ENSG00000274663.1	5S_rRNA	rRNA	NOVEL	ENST00000619782.1	5S_rRNA.14-201	rRNA	NOVEL				3	nonCoding
ENSG00000277395.1	5S_rRNA	rRNA	NOVEL	ENST00000612357.1	5S_rRNA.21-201	rRNA	NOVEL				3	nonCoding
ENSG00000278779.1	5S_rRNA	rRNA	NOVEL	ENST00000621661.1	5S_rRNA.28-201	rRNA	NOVEL				3	nonCoding
...
```
Or is this handled in rsem_postprocess? It'd be great if you could point me to the repo.

**Comment by jvivian** [comment]
Hi cchng, sorry for the delay, I ended up moving the source code into our group's account so you'd have access to the source code. The program looks up the unique ENS... ID to a table (taken from UCSC table browser) and maps it to a gene/transcript name, If that name doesn't exist, it drops it.  In my experience, it drops less than 0.5 - 1% of the genes / transcripts.

https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/gencode_hugo_mapping/gencode_hugo_map.py
