### ISSUE TITLE
Mango not available on https://quay.io/organization/ucsc_cgl

### ISSUE THREAD

**Issue by akmorrow13** [BD2KGenomics/cgl-docker-lib#270]
Mango is not yet available on https://quay.io/organization/ucsc_cgl. Is there a separate build we have to run to get mango up?

**Comment by fnothaft** [comment]
Ah, no. @jvivian needs to do something manually to make the container publicly available.

**Comment by jvivian** [comment]
I don't actually see the mango container on Quay to make public, let me try and add it manually.

**Comment by jvivian** [comment]
@akmorrow13 — Both of these should work now:

```
docker pull quay.io/ucsc_cgl/mango:0.0.1--058ccbc14bf3ff81695ae67c1a70134d1900f07f
docker pull quay.io/ucsc_cgl/mango:latest
```

**Comment by akmorrow13** [comment]
Great! Thanks @jvivian !
