### ISSUE TITLE
Human_Homo_sapiens/hg38_GENCODE_v23_basic.bed.gz does not exist for BamQC

### ISSUE THREAD

**Issue by akmorrow13** [BD2KGenomics/cgl-docker-lib#286]
https://downloads.sourceforge.net/project/rseqc/BED/Human_Homo_sapiens/hg38_GENCODE_v23_basic.bed.gz does not exist at https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/bamQC/Dockerfile#L18

**Comment by jvivian** [comment]
@akmorrow13 — Thanks for opening this; I'm assuming this is causing all of the PRs to fail?

**Comment by akmorrow13** [comment]
@jvivian yes, this is causing all PRs to fail. I made PR https://github.com/BD2KGenomics/cgl-docker-lib/pull/288 which is a temporary fix bumping to v24, but we may want something more permanent in the future
