### ISSUE TITLE
BamQC Makefile fails with unknown -f flag

### ISSUE THREAD

**Issue by akmorrow13** [BD2KGenomics/cgl-docker-lib#287]
`docker tag -f quay.io/ucsc_cgl/bamqc:1.0--a5b6a69bdf4fcc9ef7959d98e53259e0218c7a52 quay.io/ucsc_cgl/bamqc:latest` at https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/bamQC/Makefile#L10 fails with 
`unknown shorthand flag: 'f' in -f`

**Comment by jvivian** [comment]
@akmorrow13 — I guess `-f` is deprecated currently, but isn't deprecated on the jenkins build server (since so many of the makefiles have `-f` in them).  I'll remove it in my fix for #286 and see if it causes issues.
