### ISSUE TITLE
Containerize: SnpEff

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/cgl-docker-lib#37]

**Comment by arkal** [comment]
https://github.com/arkal/dockernator/blob/master/toil_dockers/05_snpEff_Dockerfile

**Comment by arkal** [comment]
https://github.com/arkal/toil_docker_wrappers/blob/master/snpeff_wrapper.sh

**Comment by jvivian** [comment]
Thanks Arjun -- I'll be adding a basic unittest and a Makefile to comply with the standards for our other containers so continuous integration works.   Might want to adjust your wrapper to also `chown` GID:  https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/gatk/runtime/wrapper.sh

**Comment by arkal** [comment]
Mine does chown GID. instead of 2lines i use the format line to do it in
one line

On Fri, Oct 16, 2015 at 2:02 PM, John Vivian notifications@github.com
wrote:

> Thanks Arjun -- I'll be adding a basic unittest and a Makefile to comply
> with the standards for our other containers so continuous integration
> works. Might want to adjust your wrapper to also chown GID:
> https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/gatk/runtime/wrapper.sh
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BD2KGenomics/cgl-docker-lib/issues/37#issuecomment-148786910
> .

## 

Arjun Arkal Rao

PhD Student,
Haussler Lab,
UC Santa Cruz,
USA

aarao@ucsc.edu

**Comment by jvivian** [comment]
oh duh, missed that. Thanks! I'll format my wrappers to follow that convention.

**Comment by heuermh** [comment]
Sorry to comment on a closed issue, but this came up in our docker images as well:  how do you intend to retrieve and stage the databases that SnpEff needs to run?

One idea would be to bake them into the docker image, so that they don't have to be read from shared disk or downloaded every time the image is run.

**Comment by hannes-ucsc** [comment]
Lets continue this discussion on #45.
