### ISSUE TITLE
Create "build everything" mode for CI

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgl-docker-lib#39]
It is good to have a mode that only builds and pushes containers that have changed since the last build. But we also need a way to determine periodically whether a Dockerfile's dependencies are still satisfied. This includes the base image version, packages installed into the container via the native package manager and URLs to downloaded source or binary tarballs.

This mode should be triggered periodically but it shouldn't push anything.

**Comment by jvivian** [comment]
Would this possibly be as easy as:
1.  Modifying the jenkins.py CI script to accept a flag, indicating "build all / no push"
2. Creating a second "build" (not sure that's the right word) called "cgl-docker-build-scheduled" that is almost identical to cgl-docker-build except it:
   1.  is scheduled to build at the interval we choose, not on push/PR
   2.  passes the appropriate flag to jenkins.py upon shell execution.

**Comment by hannes-ucsc** [comment]
Yes

**Comment by jvivian** [comment]
In this case, there is no push -- so what notification (besides checking the jenkins page) do we have in the case of build failure?

**Comment by hannes-ucsc** [comment]
Jenkins can send emails but I think the failed build icon is sufficient. I look at the Jenkins page like 50 times a day.

**Comment by jvivian** [comment]
I also realized that this will require a _separate_ jenkins build (as discussed) so its really a non-issue as it will have its own tab.

**Comment by jvivian** [comment]
Periodic build will run once a week on monday morning around 8AM, so i'll know by the time I get in if something broke.
