### ISSUE TITLE
SnpEff: Consider baking reference database into image

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgl-docker-lib#45]
https://github.com/BD2KGenomics/cgl-docker-lib/issues/37#issuecomment-150264986

**Comment by heuermh** [comment]
I.e., SnpEff 4.1l (build 2015-10-03) downloads the following for GRCh38 assembly

``` bash
$ du -hs GRCh38.81/*
6.7M    GRCh38.81/motif.bin
 40K    GRCh38.81/pwms.bin
 14M    GRCh38.81/regulation_A549.bin
...
7.4M    GRCh38.81/regulation_Osteobl.bin
 35M    GRCh38.81/sequence.1.bin
...
1.7M    GRCh38.81/sequence.Y.bin
101M    GRCh38.81/snpEffectPredictor.bin

$ du -hs GRCh38.81/
699M    GRCh38.81/
```

**Comment by hannes-ucsc** [comment]
I'm leaning towards baking this into the image. Imagine running 100 samples on a Toil cluster with 10 worker nodes. With the db baked in, the data would be downloaded 10 times and then cached on each node. With db downloaded on-the-fly, it would be downloaded 100 times. It also adds an external dependency that could break a workflow if, for example, the server hosting the db were down.

John says it would mean having multiple reference-specific versions of the image but the creation of those can and should be automated.

**Comment by arkal** [comment]
I pass in a tarball containing the database and a custom config file to my run_snpEff module. The tarball is decompressed to the folder I will be passing to teh docker image as /data. I have to do this because my reference:gtf is not available in snpEff's databse. You could consider it as well. That way you have just a single docker image for snpeff.

**Comment by hannes-ucsc** [comment]
I'm not worried about having multiple images per se. Generating multiple Dockerfiles from a template at build time can be done in 5 lines of Python. I _am_ worried about efficiency and usability. To handle your use case, @arkal, we should also offer a generic SnpEff image that does not have any db built-in.

**Comment by hannes-ucsc** [comment]
s/built-in/baked-in/

**Comment by hannes-ucsc** [comment]
John points out that there are 2500 different databases so it would only make sense bake in the most common ones.

**Comment by jvivian** [comment]
I'm thinking h19, hg38 and GRCh38.81?

@arkal -- is your custom gencode database for hg19? If so, would you be able to share the tarball with me?

**Comment by arkal** [comment]
hg19 + gencode v19. Give me a location to drop it at and I can scp it to you

On Fri, Oct 23, 2015 at 11:13 AM, John Vivian notifications@github.com
wrote:

> I'm thinking h19, hg38 and GRCh38.81?
> 
> @arkal https://github.com/arkal -- is your custom gencode database for
> hg19? If so, would you be able to share the tarball with me?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BD2KGenomics/cgl-docker-lib/issues/45#issuecomment-150652065
> .

## 

Arjun Arkal Rao

PhD Student,
Haussler Lab,
UC Santa Cruz,
USA

aarao@ucsc.edu

**Comment by hannes-ucsc** [comment]
Please host @arkal's db in a "folder" in the S3 bucket for static inputs (forgot the name) and provide a README alongside it that explains how it was derived, ideally including the specific commands.

**Comment by hannes-ucsc** [comment]
Post-pone until SnipEff is actually used.

**Comment by hannes-ucsc** [comment]
There are too many reference databases making it impractical to bake them all in. Also, users are likely to want to use their own, e.g. @arkal.
