### ISSUE TITLE
Encapsulate entire toil pipeline in an image

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/cgl-docker-lib#50]
Based on emails from Melissa and Olena, we need to be able to ship our collaborators a single image that **easily** lets them run our pipeline on a single sample locally.

**Comment by arkal** [comment]
Are you thinking of something like what Kyle does where the pipeline runs in one container and it talks to all the others?

**Comment by jvivian** [comment]
With the refactoring and [release of documentation for the rna-seq pipeline](https://github.com/BD2KGenomics/toil-scripts/blob/master/rnaseq-unc/README.md) I'm going to put a pin in this.  The new RNA-seq pipeline has no dependencies besides Docker and Toil, and if a user has privileges to install and run Docker, installing Toil should be trivial, so nothing is really gained by containerizing the entire project into an image except possibly for distribution reasons. 

 Also given the way mounting works and running Toil at scale requires a batch system, this doesn't seem like a useful project to pursue at the moment.
