### ISSUE TITLE
Fix all cgl-docker-lib tests

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/cgl-docker-lib#55]
Given the fact that many tool's help menus return non-zero exit codes (doh!), Hannes and I discussed an easy solution which is to catch stdout from a tool invocation and ensure a string specific to that tool is present.

**Comment by hannes-ucsc** [comment]
I'm assuming @jvivian is working on this.

**Comment by jvivian** [comment]
Tests pass now, but are far from robust.  stdout is parsed for keywords as opposed to looking at exit code.  A rotating student in the future could be tasked with writing "real" tests, where each tool has a command that is tested with a dummy file or something.
